name: Setup

description: Setup Node.js, cache and install dependencies

inputs:
  node_version:
    description: Node.js version
    required: false
    default: '16'

runs:
  using: composite
  steps:
    - name: Checkout all commits
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup git user to "Bot"
      shell: bash
      run: git config user.email "-" && git config user.name "Bot"

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        cache: npm
        node-version: ${{ inputs.node_version }}
        registry-url: https://registry.npmjs.org

    - name: npm ci
      shell: bash
      run: npm ci --no-progress
