name: Release

description: Release packages

inputs:
  github_token:
    description: GitHub token
    required: true
  npm_token:
    description: NPM token
    required: true
  docker_username:
    description: Docker username
    required: true
  docker_password:
    description: Docker password
    required: true

runs:
  using: composite
  steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}

    - name: Version
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm_token }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: bash
      run: npx nx run-many --target=version --all

    - name: Tag last-release
      shell: bash
      run: git tag -f last-release

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.github_token }}
        branch: ${{ github.ref }}
        force: true
        tags: true
