name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: CI with Node.js ${{ matrix.node_version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [14, 16]

    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: ${{ matrix.node_version }}

      - name: Test
        uses: ./.github/actions/test

  release:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    needs: [test]

    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup

      - name: Release
        uses: ./.github/actions/release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          npm_token: ${{ secrets.NPM_TOKEN }}
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
